apiVersion: v1
kind: Service
metadata:
  name: foosrefmanagement-nginx
spec:
  type: LoadBalancer
  selector:
    app: foosrefmanagement-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80