apiVersion: apps/v1
kind: Deployment
metadata:
  name: foosrefmanagement-nginx
  labels:
    app: foosrefmanagement-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foosrefmanagement-nginx
  template:
    metadata:
      labels:
        app: foosrefmanagement-nginx
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: foosrefmanagement-staticfiles-pvc
        - name: media
          persistentVolumeClaim:
            claimName: foosrefmanagement-media-pvc
      containers:
        - name: foosrefmanagement-nginx
          image: nkuznetsov44/foosrefmanagement-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/staticfiles
              name: staticfiles
            - mountPath: /usr/src/app/media
              name: media
