apiVersion: v1
kind: PersistentVolume
metadata:
  name: foosrefmanagement-pgdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage/k3s-data/foosrefmanagement/pgdata
    server: 192.168.88.99
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foosrefmanagement-media-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage/k3s-data/foosrefmanagement/media
    server: 192.168.88.99
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foosrefmanagement-staticfiles-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage/k3s-data/foosrefmanagement/staticfiles
    server: 192.168.88.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foosrefmanagement-pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foosrefmanagement-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foosrefmanagement-staticfiles-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
