apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikijs-pgdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage/k3s-data/wikijs/pgdata
    server: 192.168.88.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs