apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      volumes:
        - name: homer-assets
          persistentVolumeClaim:
            claimName: homer-assets-pvc
      containers:
        - name: homer
          image: b4bz/homer
          ports:
            - containerPort: 8080
          env:
            - name: INIT_ASSETS
              value: "0"
          volumeMounts:
            - mountPath: /www/assets
              name: homer-assets
