apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.2
  selector:
    app: homer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080