apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-assets-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage/k3s-data/homer
    server: 192.168.88.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-assets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
