apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.3
  selector:
    app: deluge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8112