apiVersion: v1
kind: Service
metadata:
  name: foosrefmanagement-test-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.101
  selector:
    app: foosrefmanagement-test-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80